#!/usr/bin/env python
from pypi_client.exceptions import catch
from pypi_client.management import manage

if __name__ == '__main__':
    catch(manage)()
